import type { Club } from "../model/types";

export const CLUBS: Club[] = [
  {
    id: "club-providencia",
    name: "Club Deportivo Providencia",
    description: "El club más exclusivo de la zona oriente de Santiago. Contamos con instalaciones de primer nivel para pádel, tenis y squash, rodeadas de áreas verdes y estacionamiento amplio. Nuestro equipo de profesionales está disponible para clases particulares y grupales.",
    address: "Av. Los Leones 1450, Providencia",
    city: "Santiago",
    phone: "+56 2 2234 5678",
    email: "info@clubprovidencia.cl",
    openingHours: "Lunes a Domingo: 07:00 - 23:00",
    coverImage: "/placeholder-club-1.jpg",
    gallery: ["/placeholder-club-1a.jpg", "/placeholder-club-1b.jpg", "/placeholder-club-1c.jpg"],
    rating: 4.8,
    sportIds: ["padel", "tenis", "squash"],
  },
  {
    id: "club-las-condes",
    name: "Racquet Club Las Condes",
    description: "Centro deportivo especializado en deportes de raqueta con más de 15 años de trayectoria. Canchas con iluminación LED de última generación y superficie profesional. Organizamos torneos mensuales y ofrecemos programas de entrenamiento para todos los niveles.",
    address: "Av. Kennedy 7200, Las Condes",
    city: "Santiago",
    phone: "+56 2 2345 6789",
    email: "contacto@racquetlascondes.cl",
    openingHours: "Lunes a Sábado: 06:00 - 22:00 | Domingo: 08:00 - 20:00",
    coverImage: "/placeholder-club-2.jpg",
    gallery: ["/placeholder-club-2a.jpg", "/placeholder-club-2b.jpg", "/placeholder-club-2c.jpg"],
    rating: 4.5,
    sportIds: ["padel", "tenis", "racquetball"],
  },
  {
    id: "club-vitacura",
    name: "Pádel & Tennis Vitacura",
    description: "Club boutique dedicado exclusivamente al pádel y tenis. Nuestras canchas de cristal panorámico ofrecen una experiencia única. Contamos con cafetería, pro shop y vestuarios premium con sauna.",
    address: "Av. Vitacura 3520, Vitacura",
    city: "Santiago",
    phone: "+56 2 2456 7890",
    email: "reservas@ptv.cl",
    openingHours: "Lunes a Viernes: 07:00 - 23:00 | Fin de semana: 08:00 - 22:00",
    coverImage: "/placeholder-club-3.jpg",
    gallery: ["/placeholder-club-3a.jpg", "/placeholder-club-3b.jpg", "/placeholder-club-3c.jpg"],
    rating: 4.9,
    sportIds: ["padel", "tenis"],
  },
  {
    id: "club-nunoa",
    name: "Squash & Racquet Ñuñoa",
    description: "El único club de Santiago con canchas profesionales de squash y racquetball. Sede de los campeonatos nacionales de squash. Ofrecemos también canchas de pádel con techado completo para jugar en cualquier clima.",
    address: "Av. Irarrázaval 2800, Ñuñoa",
    city: "Santiago",
    phone: "+56 2 2567 8901",
    email: "hola@squashnunoa.cl",
    openingHours: "Lunes a Domingo: 06:30 - 22:30",
    coverImage: "/placeholder-club-4.jpg",
    gallery: ["/placeholder-club-4a.jpg", "/placeholder-club-4b.jpg", "/placeholder-club-4c.jpg"],
    rating: 4.6,
    sportIds: ["squash", "racquetball", "padel"],
  },
];
