import type { Court } from "../model/types";

export const COURTS: Court[] = [
  // Club Providencia (3 courts)
  {
    id: "court-prov-1",
    name: "Cancha Central Pádel",
    clubId: "club-providencia",
    sportId: "padel",
    surface: "cesped-sintetico",
    dimensions: "20m x 10m",
    pricePerHour: 18000,
    amenities: ["iluminacion", "techado", "vestuarios", "estacionamiento"],
    image: "/placeholder-court-1.jpg",
    isActive: true,
  },
  {
    id: "court-prov-2",
    name: "Cancha Tenis 1",
    clubId: "club-providencia",
    sportId: "tenis",
    surface: "cemento",
    dimensions: "23.77m x 10.97m",
    pricePerHour: 15000,
    amenities: ["iluminacion", "vestuarios", "estacionamiento"],
    image: "/placeholder-court-2.jpg",
    isActive: true,
  },
  {
    id: "court-prov-3",
    name: "Cancha Squash A",
    clubId: "club-providencia",
    sportId: "squash",
    surface: "parquet",
    dimensions: "9.75m x 6.4m",
    pricePerHour: 12000,
    amenities: ["iluminacion", "vestuarios"],
    image: "/placeholder-court-3.jpg",
    isActive: true,
  },
  // Racquet Club Las Condes (3 courts)
  {
    id: "court-lc-1",
    name: "Pádel Premium",
    clubId: "club-las-condes",
    sportId: "padel",
    surface: "cesped-sintetico",
    dimensions: "20m x 10m",
    pricePerHour: 22000,
    amenities: ["iluminacion", "techado", "vestuarios", "estacionamiento"],
    image: "/placeholder-court-4.jpg",
    isActive: true,
  },
  {
    id: "court-lc-2",
    name: "Tenis Center Court",
    clubId: "club-las-condes",
    sportId: "tenis",
    surface: "cemento",
    dimensions: "23.77m x 10.97m",
    pricePerHour: 20000,
    amenities: ["iluminacion", "techado", "vestuarios", "estacionamiento"],
    image: "/placeholder-court-5.jpg",
    isActive: true,
  },
  {
    id: "court-lc-3",
    name: "Racquetball Court 1",
    clubId: "club-las-condes",
    sportId: "racquetball",
    surface: "parquet",
    dimensions: "12.2m x 6.1m",
    pricePerHour: 14000,
    amenities: ["iluminacion", "vestuarios"],
    image: "/placeholder-court-6.jpg",
    isActive: true,
  },
  // Pádel & Tennis Vitacura (3 courts)
  {
    id: "court-vit-1",
    name: "Pádel Panorámico 1",
    clubId: "club-vitacura",
    sportId: "padel",
    surface: "cristal",
    dimensions: "20m x 10m",
    pricePerHour: 25000,
    amenities: ["iluminacion", "techado", "vestuarios", "estacionamiento"],
    image: "/placeholder-court-7.jpg",
    isActive: true,
  },
  {
    id: "court-vit-2",
    name: "Pádel Panorámico 2",
    clubId: "club-vitacura",
    sportId: "padel",
    surface: "cristal",
    dimensions: "20m x 10m",
    pricePerHour: 25000,
    amenities: ["iluminacion", "techado", "vestuarios", "estacionamiento"],
    image: "/placeholder-court-8.jpg",
    isActive: true,
  },
  {
    id: "court-vit-3",
    name: "Tenis Clay Court",
    clubId: "club-vitacura",
    sportId: "tenis",
    surface: "cemento",
    dimensions: "23.77m x 10.97m",
    pricePerHour: 22000,
    amenities: ["iluminacion", "vestuarios", "estacionamiento"],
    image: "/placeholder-court-9.jpg",
    isActive: true,
  },
  // Squash & Racquet Ñuñoa (3 courts)
  {
    id: "court-nun-1",
    name: "Squash Profesional 1",
    clubId: "club-nunoa",
    sportId: "squash",
    surface: "parquet",
    dimensions: "9.75m x 6.4m",
    pricePerHour: 10000,
    amenities: ["iluminacion", "vestuarios"],
    image: "/placeholder-court-10.jpg",
    isActive: true,
  },
  {
    id: "court-nun-2",
    name: "Racquetball Pro",
    clubId: "club-nunoa",
    sportId: "racquetball",
    surface: "parquet",
    dimensions: "12.2m x 6.1m",
    pricePerHour: 11000,
    amenities: ["iluminacion", "vestuarios", "estacionamiento"],
    image: "/placeholder-court-11.jpg",
    isActive: true,
  },
  {
    id: "court-nun-3",
    name: "Pádel Techado",
    clubId: "club-nunoa",
    sportId: "padel",
    surface: "cesped-sintetico",
    dimensions: "20m x 10m",
    pricePerHour: 16000,
    amenities: ["iluminacion", "techado", "vestuarios", "estacionamiento"],
    image: "/placeholder-court-12.jpg",
    isActive: true,
  },
];
